# Generated by Django 5.2.17 on 2026-09-27 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('ordem', models.SmallIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'produto de interesse',
                'verbose_name_plural': 'produtos de interesse',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'rede social',
                'verbose_name_plural': 'redes sociais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('nome_norm', models.CharField(editable=False, max_length=80)),
            ],
            options={
                'verbose_name': 'cidade',
                'verbose_name_plural': 'cidades',
                'ordering': ['nome', 'uf'],
                'constraints': [models.UniqueConstraint(fields=('nome_norm', 'uf'), name='uniq_cidade_nome_uf')],
            },
        ),
        migrations.CreateModel(
            name='Revendedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=120, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Use apenas dígitos.'), django.core.validators.MaxLengthValidator(11)], verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('endereco', models.CharField(blank=True, max_length=160, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=80)),
                ('cep', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'CEP deve ter 8 dígitos (sem hífen).')], verbose_name='CEP')),
                ('vende_outras_marcas', models.BooleanField(default=False, verbose_name='vende outras marcas')),
                ('ja_revende', models.BooleanField(default=False, verbose_name='já revende')),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('desativado_em', models.DateTimeField(blank=True, null=True, verbose_name='desativada em')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revendedoras', to='prospeccao.cidade', verbose_name='cidade')),
                ('promotora', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revendedoras', to=settings.AUTH_USER_MODEL, verbose_name='promotora')),
            ],
            options={
                'verbose_name': 'revendedora',
                'verbose_name_plural': 'revendedoras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RevendedoraInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='prospeccao.produtointeresse')),
                ('revendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_vinculados', to='prospeccao.revendedora')),
            ],
            options={
                'verbose_name': 'interesse da revendedora',
                'verbose_name_plural': 'interesses das revendedoras',
            },
        ),
        migrations.AddField(
            model_name='revendedora',
            name='interesses',
            field=models.ManyToManyField(related_name='revendedoras', through='prospeccao.RevendedoraInteresse', to='prospeccao.produtointeresse', verbose_name='interesses'),
        ),
        migrations.CreateModel(
            name='RevendedoraMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='prospeccao.marca')),
                ('revendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_vinculadas', to='prospeccao.revendedora')),
            ],
            options={
                'verbose_name': 'marca da revendedora',
                'verbose_name_plural': 'marcas das revendedoras',
            },
        ),
        migrations.AddField(
            model_name='revendedora',
            name='marcas_revendidas',
            field=models.ManyToManyField(related_name='revendedoras', through='prospeccao.RevendedoraMarca', to='prospeccao.marca', verbose_name='marcas revendidas'),
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$', 'Use apenas dígitos.')], verbose_name='número')),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('outro', 'Outro')], default='whatsapp', max_length=20)),
                ('principal', models.BooleanField(default=False)),
                ('revendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='prospeccao.revendedora')),
            ],
            options={
                'verbose_name': 'telefone',
                'verbose_name_plural': 'telefones',
            },
        ),
        migrations.CreateModel(
            name='RedeSocialVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=120, verbose_name='perfil')),
                ('para_contato', models.BooleanField(default=False, verbose_name='para contato')),
                ('para_seguir', models.BooleanField(default=False, verbose_name='para seguir')),
                ('rede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='prospeccao.redesocial')),
                ('revendedora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='prospeccao.revendedora')),
            ],
            options={
                'verbose_name': 'rede social da revendedora',
                'verbose_name_plural': 'redes sociais das revendedoras',
                'constraints': [models.UniqueConstraint(fields=('revendedora', 'rede'), name='uniq_revend_rede')],
            },
        ),
        migrations.AddConstraint(
            model_name='revendedorainteresse',
            constraint=models.UniqueConstraint(fields=('revendedora', 'produto'), name='uniq_revend_produto'),
        ),
        migrations.AddConstraint(
            model_name='revendedoramarca',
            constraint=models.UniqueConstraint(fields=('revendedora', 'marca'), name='uniq_revend_marca'),
        ),
        migrations.AddIndex(
            model_name='revendedora',
            index=models.Index(fields=['promotora', 'criado_em'], name='ix_revend_promotora'),
        ),
        migrations.AddIndex(
            model_name='revendedora',
            index=models.Index(fields=['ja_revende'], name='ix_revend_ja_revende'),
        ),
        migrations.AddIndex(
            model_name='revendedora',
            index=models.Index(fields=['cidade'], name='ix_revend_cidade'),
        ),
        migrations.AddIndex(
            model_name='telefone',
            index=models.Index(fields=['numero'], name='ix_telefone_numero'),
        ),
        migrations.AddConstraint(
            model_name='telefone',
            constraint=models.UniqueConstraint(fields=('revendedora', 'numero'), name='uniq_revend_telefone'),
        ),
    ]
