# Generated by Django 5.2.17 on 2026-09-27 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospeccao', '0002_seed_catalogos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revendedora',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve ter 11 dígitos (sem pontos/hífen).')], verbose_name='CPF'),
        ),
    ]
