# Generated by Django 5.2.17 on 2026-09-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('promotora', 'Promotora'), ('gestor', 'Gestor')], default='promotora', max_length=20)),
                ('nome_completo', models.CharField(max_length=120)),
                ('territorio', models.CharField(blank=True, max_length=120)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=64)),
                ('obj_id', models.BigIntegerField()),
                ('acao', models.CharField(choices=[('create', 'criação'), ('update', 'edição'), ('delete', 'exclusão')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'indexes': [models.Index(fields=['model', 'obj_id'], name='ix_audit_model_obj'), models.Index(fields=['criado_em'], name='ix_audit_criado')],
            },
        ),
    ]
